@url=http://localhost:8080

###

GET {{url}}/api/wordy
Content-Type: application/json


###

POST {{url}}/api/wordy
Content-Type: application/json

{"id": 1, "message": "submit message"}

###

POST {{url}}/api/wordy
Content-Type: application/json

{"id": 2, "message": "Second Message"}

###

POST {{url}}/api/wordy
Content-Type: application/json

{"id": 900, "message": "Long ago message"}